"""add refresh token table

Revision ID: 11813fd78897
Revises: 236bc1f3b79f
Create Date: 2026-05-09 15:36:53.141191

"""

from collections.abc import Sequence

revision: str = "11813fd78897"
down_revision: str | None = "236bc1f3b79f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
