"""add_logo_url_to_organiser_templates

Revision ID: 3420dcb18a19
Revises: a9fb7383568a
Create Date: 2026-05-12 16:17:55.525568

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "3420dcb18a19"
down_revision: str | None = "a9fb7383568a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organiser_templates",
        sa.Column("logo_url", sa.String(length=1024), nullable=True),
    )
    op.add_column(
        "organiser_templates",
        sa.Column("logo_public_id", sa.String(length=512), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organiser_templates", "logo_public_id")
    op.drop_column("organiser_templates", "logo_url")
    # ### end Alembic commands ###
