"""add template tables

Revision ID: a9fb7383568a
Revises: e3714af1afe9
Create Date: 2026-05-12 10:51:41.046641

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "a9fb7383568a"
down_revision: str | None = "e3714af1afe9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "canvas_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("thumbnail_url", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_platform_templates_id"), "platform_templates", ["id"], unique=False
    )
    op.create_table(
        "organiser_templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organizer_id", sa.Uuid(), nullable=False),
        sa.Column("platform_template_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "canvas_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("default_caption", sa.String(length=255), nullable=True),
        sa.Column("destination_link", sa.String(length=255), nullable=True),
        sa.Column("thumbnail_url", sa.String(length=255), nullable=True),
        sa.Column("access_type", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("share_slug", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organizer_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["platform_template_id"], ["platform_templates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("share_slug"),
    )
    op.create_index(
        op.f("ix_organiser_templates_id"), "organiser_templates", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_organiser_templates_organizer_id"),
        "organiser_templates",
        ["organizer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organiser_templates_platform_template_id"),
        "organiser_templates",
        ["platform_template_id"],
        unique=False,
    )
    op.create_table(
        "badges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("participant_name", sa.String(length=255), nullable=False),
        sa.Column("profile_url", sa.String(length=255), nullable=True),
        sa.Column("badge_image_url", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["template_id"], ["organiser_templates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_badges_id"), "badges", ["id"], unique=False)
    op.create_index(
        op.f("ix_badges_template_id"), "badges", ["template_id"], unique=False
    )
    op.create_table(
        "template_hashtags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("hashtag", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["template_id"], ["organiser_templates.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_template_hashtags_hashtag"),
        "template_hashtags",
        ["hashtag"],
        unique=False,
    )
    op.create_index(
        op.f("ix_template_hashtags_id"), "template_hashtags", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_template_hashtags_template_id"),
        "template_hashtags",
        ["template_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_template_hashtags_template_id"), table_name="template_hashtags"
    )
    op.drop_index(op.f("ix_template_hashtags_id"), table_name="template_hashtags")
    op.drop_index(op.f("ix_template_hashtags_hashtag"), table_name="template_hashtags")
    op.drop_table("template_hashtags")
    op.drop_index(op.f("ix_badges_template_id"), table_name="badges")
    op.drop_index(op.f("ix_badges_id"), table_name="badges")
    op.drop_table("badges")
    op.drop_index(
        op.f("ix_organiser_templates_platform_template_id"),
        table_name="organiser_templates",
    )
    op.drop_index(
        op.f("ix_organiser_templates_organizer_id"), table_name="organiser_templates"
    )
    op.drop_index(op.f("ix_organiser_templates_id"), table_name="organiser_templates")
    op.drop_table("organiser_templates")
    op.drop_index(op.f("ix_platform_templates_id"), table_name="platform_templates")
    op.drop_table("platform_templates")
    # ### end Alembic commands ###
